OWNER_NAME="𝑰𝒃𝒓𝒂𝒉𝒊𝒎 𝑨𝒅𝒂𝒎𝒔"
PREFIX="."
PUBLIC_MODE='yes'
AUTO_READ_STATUS="yes"
AUTO_DOWNLOAD_STATUS="no"
BOT_NAME= "𝘽𝙈𝙒-𝙈𝘿"
IMAGE_MENU= "https://telegra.ph/file/071f797dda6aef5ae3877.jpg"
NUMERO_OWNER= ""
OWNER_NAME= "᚛Ibrahim Adams᚜"
DATABASE_URL= ""
WARN_COUNT= ""
OPENAI_API_KEY= ""
STARTING_BOT_MESSAGE='yes'
ANTI_DELETE_MESSAGE='yes'

